// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.9
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider(
    {
        effect:"parallax",
        prev:"<",
        next:">",
        duration:20*100,
        delay:20*100,
        width:533,
        height:360,
        autoPlay:true,
        autoPlayVideo:false,
        playPause:true,
        stopOnHover:false,
        loop:false,
        bullets:0,
        caption:true,
        captionEffect:"parallax",
        controls:true,
        controlsThumb:true,
        responsive:1,
        fullScreen:true,
        gestures:2,
        onBeforeStep:0,
        images:0
    }

);
